[SPECTROGRAM]
fft_size = 512
step_size = 64
freq_cutoffs = [ 500, 10000,]
thresh = 6.25
transform_type = "log_spect"

[TRAIN]
normalize_spectrograms = "Yes"
num_epochs = 50
val_error_step = 1
checkpoint_step = 1
save_only_single_checkpoint_file = true
patience = 4
replicates = 4
models = "TweetyNet"
root_results_dir = "~/Documents/data/BFSongRepository/vak/gr41rd51"
batch_size = 11

[PREP]
labelset = "iabcdefgjkm"
data_dir = "~/Documents/data/BFSongRepository/gr41rd51/061912/train_subset"
output_dir = "~/Documents/data/BFSongRepository/vak/gr41rd51"
audio_format = "cbin"
annot_format = "notmat"
test_dur = 0
train_dur = 60
val_dur = 80
root_results_dir = "./results/BFSongRepository/gr41rd51"
csv_path = "/home/art/Documents/data/BFSongRepository/vak/gr41rd51/train_subset_prep_200608_095539.csv"

[DATALOADER]
window_size = 88

[TweetyNet.optimizer]
lr = 0.001
