[PREP]
data_dir = "~/Documents/data/BFSongRepository/gr41rd51/062312/has_notmat/"
output_dir = "results/BFSongRepository/gr41rd51/predict"
audio_format = "cbin"

[SPECT_PARAMS]
fft_size = 512
step_size = 64
freq_cutoffs = [ 500, 10000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[TweetyNet.optimizer]
lr = 0.001

[PREDICT]
checkpoint_path = "~/Documents/repos/coding/birdsong/tweetynet/results/BFSongRepository/gr41rd51/results_200620_165008/TweetyNet/checkpoints/max-val-acc-checkpoint.pt"
labelmap_path = "~/Documents/repos/coding/birdsong/tweetynet/results/BFSongRepository/gr41rd51/results_200620_165008/labelmap.json"
models = "TweetyNet"
batch_size = 11
num_workers = 4
device = "cuda"
spect_scaler_path = "~/Documents/repos/coding/birdsong/tweetynet/results/BFSongRepository/gr41rd51/results_200620_165008/StandardizeSpect"
output_dir = "results/BFSongRepository/gr41rd51/predict"
annot_csv_filename = "gr41rd51.062312.annot.csv"
